config/routes.rb
Rails.application.routes.draw do
  # resources :urls
  root to: 'urls#index'

  resources :urls, only: [:create, :destroy]

  get '/:token', to: 'urls#show',
                 constraints: { token: /[a-zA-Z0-9]{7}/ },
                 as: :shortened
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :original_url, presence: true

  before_validation :generate_token

  private

  def generate_token
    self.token = TokenGenerator.generate(original_url) if token.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = all_urls_desc
    @url = Url.new
  end

  def show
    @url = Url.find_by(token: params[:token])

    if @url
      redirect_to @url.original_url, status: :moved_permanently
    else
      redirect_to root_path, flash: { error: 'Url was not found.' }
    end
  end

  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to root_path, notice: 'Url was successfully shortened.' }
      else
        format.html do
          @urls = all_urls_desc
          render :index
        end
      end
    end
  end

  def destroy
    @url = Url.find(params[:id])
    @url.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Url was successfully destroyed.' }
    end
  end

  private

  def all_urls_desc
    Url.all.order(id: :desc)
  end

  def url_params
    params.require(:url).permit(:original_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url, local: true) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-content">
    <div class="field">
     <%= form.label :original_url %>
      <%= form.text_area :original_url ,  id: :url_original_url, class:'textarea', placeholder:'Enter URL'%>
    </div>

    <div class="actions">
      <%= form.submit  value: 'Shorten Link', class:'button' %>
    </div>
  </div>
  
<% end %>

app/views/urls/index.html.erb
<%# <p id="notice"><%= notice ></p> %>
<nav class="nav-topic">
<% flash.each do |key, value| %>
  <div class="<%= key %>"><%= value %></div>
<% end %>
<h1>Shorten Url</h1>
<nav>
<div style="color:red;" class="form-content">
  <%= render 'form', url: @url %>
</div>
<br>

<%# <h1>Urls</h1> %>

<table>
  <thead>
    <tr>
      <th>Original url</th>
      <th>Shortened Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <%# <td><%= url.token ></td> %>
        <td><%= url.original_url %></td>
        <td><%= link_to shortened_url(url.token), shortened_url(url.token) %></td>
        <%# <td><%= link_to 'Show', url ></td> %>
        <%# <td><%= link_to 'Edit', edit_url_path(url) ></td> %>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# <%= link_to 'New Url', new_url_path > %>